<a href="https://colab.research.google.com/github/Ankitapaul1234/gc_ml/blob/main/numpy_campusx.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#array create
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
#2D array
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#3D array
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[2,8,6]]])
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [2, 8, 6]]])

In [ ]:
#dtpe
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [ ]:
#np.arange
a=np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [ ]:
#np.reashape
a=np.arange(1,11).reshape(5,2)  #5-->row,2-->col
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#np.ones
a=np.ones((5,4))
a
#np.zeros
b=np.zeros((3,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#np.random
a=np.random.random((4,5))
a

array([[0.97359496, 0.85791089, 0.50700322, 0.01500708, 0.53382833],
       [0.40134287, 0.65277356, 0.04139352, 0.59826254, 0.35167006],
       [0.33684079, 0.66236636, 0.51757916, 0.82394346, 0.41293557],
       [0.59777425, 0.30211478, 0.56430128, 0.7070537 , 0.90597111]])

In [ ]:
#np.identity
a=np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#np.linspace
a=np.linspace(1,11,5)
a

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [ ]:
#array attribute
#ndimm
a1=np.array([1,2,3])
a2=np.array([[1,2,3],[4,5,6]])
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[5,8,1]]])
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [ ]:
#shape
a3.shape

(2, 2, 3)

In [ ]:
a2.shape

(2, 3)

In [ ]:
#itemsize
a.itemsize

8

In [ ]:
#dtype
print(a1.dtype)

int64


In [ ]:
a2.dtype

dtype('int64')

In [ ]:
#changing
